
logging.level.org.zalando.logbook= TRACE

logbook.format.style = http
logbook.write.level = INFO

logbook.filter.enabled = true

spring.application.name=filmorate

server.port=8080
server.error.include-message=always
server.error.include-binding-errors=always

spring.web.resources.add-mappings=false
