-- Создание таблицы mpa_ratings (рейтинги)
CREATE TABLE IF NOT EXISTS mpa_ratings
(
    id   LONG PRIMARY KEY,
    name VARCHAR(10) NOT NULL UNIQUE
);

-- Создание таблицы genres (жанры)
CREATE TABLE IF NOT EXISTS genres
(
    id   LONG PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

-- Создание таблицы films
CREATE TABLE IF NOT EXISTS films
(
    id           LONG GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    description  VARCHAR(200),
    release_date DATE         NOT NULL,
    duration     INTEGER      NOT NULL CHECK (duration > 0),
    mpa_id       LONG      REFERENCES MPA_ratings (id) ON DELETE SET NULL
);

-- Создание таблицы film_genres (связь фильмов и жанров)
CREATE TABLE IF NOT EXISTS film_genres
(
    film_id  LONG REFERENCES films (id) ON DELETE CASCADE,
    genre_id LONG REFERENCES genres (id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, genre_id)
);

-- Создание таблицы users
CREATE TABLE IF NOT EXISTS users
(
    id       LONG GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    VARCHAR(255) NOT NULL UNIQUE,
    login    VARCHAR(255) NOT NULL UNIQUE,
    name     VARCHAR(255),
    birthday DATE         NOT NULL
);

-- Создание таблицы friendships (односторонняя дружба со статусом)
CREATE TABLE IF NOT EXISTS friendships
(
    user_id   LONG REFERENCES users (id) ON DELETE CASCADE,
    friend_id LONG REFERENCES users (id) ON DELETE CASCADE,
    status    VARCHAR(20) DEFAULT 'UNCONFIRMED' CHECK (status IN ('UNCONFIRMED', 'CONFIRMED')),
    PRIMARY KEY (user_id, friend_id)
);

-- Создание таблицы likes (лайки фильмов)
CREATE TABLE IF NOT EXISTS likes
(
    film_id LONG REFERENCES films (id) ON DELETE CASCADE,
    user_id LONG REFERENCES users (id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, user_id)
);

-- Заполнение справочника MPA рейтингов
MERGE INTO mpa_ratings (id, name) VALUES (1, 'G');
MERGE INTO mpa_ratings (id, name) VALUES (2, 'PG');
MERGE INTO mpa_ratings (id, name) VALUES (3, 'PG-13');
MERGE INTO mpa_ratings (id, name) VALUES (4, 'R');
MERGE INTO mpa_ratings (id, name) VALUES (5, 'NC-17');

-- Заполнение справочника жанров
MERGE INTO genres (id, name) VALUES (1, 'Комедия');
MERGE INTO genres (id, name) VALUES (2, 'Драма');
MERGE INTO genres (id, name) VALUES (3, 'Мультфильм');
MERGE INTO genres (id, name) VALUES (4, 'Триллер');
MERGE INTO genres (id, name) VALUES (5, 'Документальный');
MERGE INTO genres (id, name) VALUES (6, 'Боевик');